name: Deploy Homolog

on:
  workflow_dispatch:

jobs:
  deploy-homolog:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Homolog
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: ${{ secrets.VM_PORT }}

          script: |
            set -e

            echo "Atualizando pacotes..."

            sudo apt-get update -y

            echo "Verificando Git..."

            if ! command -v git &> /dev/null
            then
              echo "Git não encontrado. Instalando..."
              sudo apt-get install -y git
            fi

            echo "Verificando Docker..."

            if ! command -v docker &> /dev/null
            then
              echo "Docker não encontrado. Instalando..."
              sudo apt-get install -y docker.io
              sudo systemctl enable docker
              sudo systemctl start docker
            fi

            echo "Verificando Docker Compose..."

            if ! command -v docker-compose &> /dev/null
            then
              echo "Docker Compose não encontrado. Instalando..."
              sudo apt-get install -y docker-compose
            fi

            echo "Criando diretório do projeto..."

            sudo mkdir -p /opt/projeto_homolog

            sudo chown -R $USER:$USER /opt/projeto_homolog

            echo "Clonando ou atualizando repositório..."

            if [ ! -d "/opt/projeto_homolog/.git" ]; then

              git clone -b homolog https://github.com/JulioSchneider1/app_financas.git /opt/projeto_homolog

            else

              cd /opt/projeto_homolog

              git fetch origin

              git checkout homolog

              git pull origin homolog

            fi

            cd /opt/projeto_homolog

            echo "Parando containers antigos..."

            docker-compose -f docker-compose.homolog.yml down || true

            echo "Subindo ambiente homolog..."

            docker-compose -f docker-compose.homolog.yml up --build -d

            echo "Containers ativos:"

            docker ps

            echo "Deploy finalizado com sucesso!"