name: Promote to Homolog

on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed

permissions:
  contents: write

jobs:
  promote:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'master' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Merge main → homolog
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git fetch origin

          git checkout -b homolog origin/homolog || git checkout homolog
          git merge origin/master --no-edit --allow-unrelated-histories

          git push origin homolog