name: Promote to Homolog

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  promote:
    needs: tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Merge main → homolog
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git fetch origin

          git checkout -b homolog origin/homolog || git checkout homolog
          git merge origin/master --no-edit --allow-unrelated-histories -X theirs 

          git push origin homolog