name: Test SSH Connection

on:
  workflow_dispatch:

jobs:
  test-ssh:
    runs-on: ubuntu-latest


    steps:
      - name: Configurar chave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H -p ${{ secrets.VM_PORT }} ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

      - name: Testar conexão SSH
        run: |
          ssh -i ~/.ssh/id_rsa \
            -p ${{ secrets.VM_PORT }} \
            ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'

            echo "Conectado com sucesso!"
            whoami
            hostname
            pwd

          EOF